require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

# Basic
AllCops:
  DisplayStyleGuide: true

  DisabledByDefault: true
  NewCops: enable

  Exclude:
    - ".git/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

  TargetRubyVersion: 3.0

# Layout
Layout:
  Enabled: true

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# TODO: remove for gem rubocop >= v2, once it'll become default
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true

# Lint
Lint:
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Lint/EmptyClass: # (new in 1.3)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true

# Metrics
Metrics:
  Enabled: true

Metrics/AbcSize:
  CountRepeatedAttributes: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
    - "spec/support/factories.rb"
    - "test/factories.rb"
    - "spec/factories.rb"
    - "test/factories/*.rb"
    - "spec/factories/*.rb"
    - "*.gemspec"

Metrics/ClassLength:
  Max: 500


Metrics/ModuleLength:
  Max: 500

Metrics/MethodLength:
  Max: 50

# Performance
Performance:
  Enabled: true

# TODO: remove for gem rubocop-performance >= v2, once it'll become default
Performance/AncestorsInclude: # (new in 1.7)
  Enabled: true

# TODO: remove for gem rubocop-performance >= v2, once it'll become default
Performance/BigDecimalWithNumericArgument: # (new in 1.7)
  Enabled: true

# TODO: remove for gem rubocop-performance >= v2, once it'll become default
Performance/BlockGivenWithExplicitBlock: # (new in 1.9)
  Enabled: true

# TODO: remove for gem rubocop-performance >= v2, once it'll become default
Performance/CollectionLiteralInLoop: # (new in 1.8)
  Enabled: true

# TODO: remove for gem rubocop-performance >= v2, once it'll become default
Performance/ConstantRegexp: # (new in 1.9)
  Enabled: true

# TODO: remove for gem rubocop-performance >= v2, once it'll become default
Performance/MethodObjectAsBlock: # (new in 1.9)
  Enabled: true

# TODO: remove for gem rubocop-performance >= v2, once it'll become default
Performance/RedundantSortBlock: # (new in 1.7)
  Enabled: true

# TODO: remove for gem rubocop-performance >= v2, once it'll become default
Performance/RedundantStringChars: # (new in 1.7)
  Enabled: true

# TODO: remove for gem rubocop-performance >= v2, once it'll become default
Performance/ReverseFirst: # (new in 1.7)
  Enabled: true

# TODO: remove for gem rubocop-performance >= v2, once it'll become default
Performance/SortReverse: # (new in 1.7)
  Enabled: true

# TODO: remove for gem rubocop-performance >= v2, once it'll become default
Performance/Squeeze: # (new in 1.7)
  Enabled: true

# TODO: remove for gem rubocop-performance >= v2, once it'll become default
Performance/StringInclude: # (new in 1.7)
  Enabled: true

# TODO: remove for gem rubocop-performance >= v2, once it'll become default
Performance/Sum: # (new in 1.8)
  Enabled: true

# Rake

Rake:
  Enabled: true

# Rspec
RSpec/AnyInstance:
  Enabled: true

RSpec/ContextWording:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  Enabled: true

RSpec/MultipleExpectations:
  Max: 3

RSpec/NamedSubject:
  IgnoreSharedExamples: true

# Style
Style:
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true

# The problem with e.g. class Foo::Bar is when Foo is not defined. Rails will try to auto-load what
# it thinks is the right file, which (pre-Rails 6.0) sometimes leads to it loading the wrong file,
# and Bar being defined in the wrong namespace. This way we can be more elastic and remove not needed nesting.
Style/ClassAndModuleChildren:
  Enabled: false

# TODO: remove for gem rubocop >= v2, once it'll become default
Style/CollectionCompact: # (new in 1.2)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

# TODO: remove for gem rubocop >= v2, once it'll become default
Style/EndlessMethod: # (new in 1.8)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Style/HashExcept: # (new in 1.7)
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/ModuleFunction:
  Enabled: false

# TODO: remove for gem rubocop >= v2, once it'll become default
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Style/NilLambda: # (new in 1.3)
  Enabled: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Style/RedundantArgument: # (new in 1.4)
  Enabled: true

# https://www.viget.com/articles/just-use-double-quoted-ruby-strings/
Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

# TODO: remove for gem rubocop >= v2, once it'll become default
Style/SwapValues: # (new in 1.1)
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WordArray:
  Enabled: false
